[package]
name = "ficha-api"
version = "0.1.0"
edition = "2024"

[dependencies]
mongodb = "2.8.1"
tokio = { version = "1.38.0", features = ["full"] }
serde = { version = "1.0.203", features = ["derive"] }
